{"name": "test_login[casedata0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '帐号或密码输入错误' == 'aasuccess1'\n  - aasuccess1\n  + 帐号或密码输入错误", "trace": "self = <test_login.Test_login object at 0x1037c3640>\ncasedata = {'channel': 'PC', 'description': '验证某某账号是否正常', 'password': '/XrJ0I8kCO6JZ6rxmTpvmg==', 'userCode': 'liuxl2', ...}\n\n    @allure.story(\"登录接口\")\n    @pytest.mark.parametrize('casedata', yaml.safe_load(open(\"data/login_data.yaml\")))\n    def test_login(self,casedata):\n        self.casedata=casedata\n        self.data = CommonTemplate().template(\"api/login.yaml\", self.casedata)\n        self.r=self.getResponse(self.data)\n        # 获取用例标题和测试用例描述\n        description = casedata.get(\"description\")\n        uri = Handle_yaml(\"api/login.yaml\").get_uri()\n        try:\n            expected_errMsg=self.casedata.get(\"veryfi\").get(\"errMsg\")\n            assert (self.r.json()[\"errMsg\"] == expected_errMsg)\n            normal_logger.info(uri+\"的\"+description+\"用例执行成功\")\n        except AssertionError as e:\n            error_logger.error(uri+\"的\"+description+\"用例执行失败:{}\".format(e))\n>           raise e\n\ntestCase/test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_login.Test_login object at 0x1037c3640>\ncasedata = {'channel': 'PC', 'description': '验证某某账号是否正常', 'password': '/XrJ0I8kCO6JZ6rxmTpvmg==', 'userCode': 'liuxl2', ...}\n\n    @allure.story(\"登录接口\")\n    @pytest.mark.parametrize('casedata', yaml.safe_load(open(\"data/login_data.yaml\")))\n    def test_login(self,casedata):\n        self.casedata=casedata\n        self.data = CommonTemplate().template(\"api/login.yaml\", self.casedata)\n        self.r=self.getResponse(self.data)\n        # 获取用例标题和测试用例描述\n        description = casedata.get(\"description\")\n        uri = Handle_yaml(\"api/login.yaml\").get_uri()\n        try:\n            expected_errMsg=self.casedata.get(\"veryfi\").get(\"errMsg\")\n>           assert (self.r.json()[\"errMsg\"] == expected_errMsg)\nE           AssertionError: assert '帐号或密码输入错误' == 'aasuccess1'\nE             - aasuccess1\nE             + 帐号或密码输入错误\n\ntestCase/test_login.py:31: AssertionError"}, "attachments": [{"name": "stdout", "source": "4a0dd9a7-18b8-46e4-9cf2-4b4b130873a1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ee764d20-817f-4568-b871-e26106b746b2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "casedata", "value": "{'channel': 'PC', 'password': '/XrJ0I8kCO6JZ6rxmTpvmg==', 'userCode': 'liuxl2', 'veryfi': {'errMsg': 'aasuccess1'}, 'description': '验证某某账号是否正常'}"}], "start": 1652169577636, "stop": 1652169577702, "uuid": "9e766a96-c1d1-4e54-8a34-2efec4fe70a4", "historyId": "9e54f0f5961ee2a0eb6043221697b907", "testCaseId": "4b629f5aeccfb06b7640d6a8f2a50152", "fullName": "testCase.test_login.Test_login#test_login", "labels": [{"name": "feature", "value": "测试登录退出模块"}, {"name": "story", "value": "登录接口"}, {"name": "parentSuite", "value": "testCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "kongdeMacBook-Air.local"}, {"name": "thread", "value": "5409-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.test_login"}]}